import {
  Avatar,
  Center,
  Divider,
  Heading,
  Tag,
  TagLabel,
} from '@chakra-ui/react';
import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';

const About: NextPage = () => {
  return (
    <div>
      <Head>
        <title>About</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <nav>
        <Center height="50px">
          <Link href="/">Home</Link>
        </Center>
      </nav>

      <Center height="50px">
        <Divider />
      </Center>

      <main>
        <Center height="50px">
          <Heading as="h1">The spectacle before us was indeed sublime.</Heading>
        </Center>
      </main>

      <Center height="50px">
        <Divider />
      </Center>

      <footer>
        <Center height="50px">
          <a
            href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            Powered by{' '}
            <span>
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                width={72}
                height={16}
              />
            </span>
          </a>
        </Center>
      </footer>
    </div>
  );
};

export default About;
